name: Image workflow

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  image-job:
    name: Image job
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v6
        with:
          tags: alexengrig/tech-showcase:0.1.0-SNAPSHOT
          push: true
